name: Publish OCI Image
on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Login to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6a58db7e0d21ca03e6c44877909e80e45217eed2 # v2

      - name: Check the version
        id: get_version
        run: |
          version="$(grep -Po "zinc:\K[0-9]+\.[0-9]+\.[0-9]+" Dockerfile)"
          echo "VERSION=$version" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@44ea916f6c540f9302d50c2b1e5a8dc071f15cdf # v4
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/zinc:${{ steps.get_version.outputs.VERSION }},${{ secrets.DOCKER_HUB_USERNAME }}/zinc:latest

      - name: Update charm metadata
        run: |
          version=${{ steps.get_version.outputs.VERSION }}
          sed -i -e "s/zinc:[0-9]\+\.[0-9]\+\.[0-9]\+/zinc:${version}/g" metadata.yaml

      # We use a Github App and token to allow Github Actions to run properly on the created PR.
      - uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_KEY }}

      - name: Create a PR to update charm
        uses: peter-evans/create-pull-request@284f54f989303d2699d373481a0cfa13ad5a6666 # v5
        id: cpr
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "chore(deps): bump zinc container image to `jnsgruk/zinc:${{ steps.get_version.outputs.VERSION }}`"
          committer: "Github Actions <github-actions@github.com>"
          author: "Github Actions <github-actions@github.com>"
          title: "Update container image to `jnsgruk/zinc:${{ steps.get_version.outputs.VERSION }}`"
          body: "Update container image to `jnsgruk/zinc:${{ steps.get_version.outputs.VERSION }}`"
          branch: "auto-container-${{ steps.get_version.outputs.VERSION }}"
          delete-branch: true
          reviewers: jnsgruk
          assignees: jnsgruk
